import "./globals.css";
import { Archivo } from "next/font/google";
import localFont from "next/font/local"

const archivo = Archivo({ subsets: ["latin"] });

const surt = localFont({
  src: '../../public/gallerymodern_webfont1.woff',
  variable: '--font-surt-bold',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={surt.className}>{children}</body>
    </html>
  );
}
